# Generated by Django 5.0.6 on 2024-07-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
